name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}   
    
    steps:
      - name: Recoger input
        run: |
          echo "Entorno seleccionado: ${{ inputs.environment }}"

      - name: Deploy Development
        run: |
          echo "Cargando variables "
          echo "API_URL is ${{ vars.API_URL }}"  
          echo "LOG_LEVEL is ${{ vars.LOG_LEVEL }}"
