name: deploy

on:
 workflow_call:
    inputs:
      environment:
        required: true
        type: string
 

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Recoger input
        run: |
          echo "Entorno seleccionado: ${{ inputs.environment }}"

      - name: Cargar variables de entorno manualmente
        run: |
          echo "${{ vars.API_URL }}" 
          echo "${{ vars.LOG_LEVEL }}" 

 
